sqlldr transmilenio/a123 control=operadores.ctl data=operadores.csv
sqlldr transmilenio/a123 control=horario.ctl data=horario.csv
sqlldr transmilenio/a123 control=ruta.ctl data=ruta.csv
sqlldr transmilenio/a123 control=troncal.ctl data=troncal.csv
sqlldr transmilenio/a123 control=portal.ctl data=portal.csv
sqlldr transmilenio/a123 control=estaciones.ctl data=estaciones.csv
sqlldr transmilenio/a123 control=vagon.ctl data=vagon.csv
sqlldr transmilenio/a123 control=detalle_ruta.ctl data=detalle_ruta.csv
sqlldr transmilenio/a123 control=servicio.ctl data=servicio.csv
sqlldr transmilenio/a123 control=fases.ctl data=fases.csv
